### ISSUE TITLE
How start this game on localhost (by downloading source codes).

### ISSUE THREAD

**Issue by sakhib-orzklv** [Priler/dino3d#11]
I downloaded source codes and tried to run it on chrome. However, it displays "that" error page, then starts loading assets, but it will still remain 0%. I mean assets won't load. But in online mode it works well

**Comment by mukhsinbek** [comment]
> I downloaded source codes and tried to run it on chrome. However, it displays "that" error page, then starts loading assets, but it will still remain 0%. I mean assets won't load. But in online mode it works well

+++++

**Comment by Priler** [comment]
Currently game can be started only on a webserver.
You can try local webserver, though.
Such as Open Server or XAMPP.
