### ISSUE TITLE
Телеграм-бот

### ISSUE THREAD

**Issue by Rifat-Fazlutdinov** [Priler/dino3d#16]
Привет) Я тут поменял логику работы бота, взглянь)
https://github.com/Rifat-Fazlutdinov/dino_bot
Telegram - @fearsd
И кстати, где тебе можно написать, чтобы я был уверен, что ты прочитаешь сообщение?
Я просто могу расширить возможности бота, а ты о них можешь и не знать)

**Comment by Valdex** [comment]
Если бы было апи...

**Comment by Priler** [comment]
Спасибо!)
Пока что функционала бота хватает, но я буду следить за твоим репозиторием.

**Comment by fearsd** [comment]
Спасибо!
