### ISSUE TITLE
Не прорисовывается дорога... и всё остальное

### ISSUE THREAD

**Issue by sadykhzadeh** [Priler/dino3d#17]
Нажал на кнопку "Играть заново", а там прорисован только динозавр.

**Comment by sadykhzadeh** [comment]
![image](https://user-images.githubusercontent.com/51178055/74591014-7ed72200-502d-11ea-975f-f948bc07e3b0.png)

**Comment by Priler** [comment]
Скриншот консоли скинь тоже
