### ISSUE TITLE
Проблемы связанные со сменой дня и ночи

### ISSUE THREAD

**Issue by Kirixo** [Priler/dino3d#19]
1. Если умереть ночью и рестартнуть игру, то игра начнётся с ночи.
![Screenshot_5](https://user-images.githubusercontent.com/45573106/74610428-e78cd000-50fb-11ea-8a36-728767273316.png)
2. Ночью что-то с текстурами странное творится.
![Screenshot_6](https://user-images.githubusercontent.com/45573106/74610442-fe332700-50fb-11ea-9c77-1e03cd21de8b.png)
3. Сделай разнообразие типо день->закат->ночь можно ещё рассвет т.е жёлтый->красный->черный(тёмно-серый или синий) +хз розовый.

**Comment by Valdex** [comment]
@Priler добавь ещё один источник света, белый желательно

**Comment by sova-kostyan** [comment]
Такая же проблема и тоже ночью. Начиная где то с 500 очков, передний план перестал отрисовываться (см. скрины) вплоть до примерно 750 очков, после чего вновь появился. и больше уже не исчезал. такое произошло только один раз из трех.

![Снимок экрана (78)](https://user-images.githubusercontent.com/47751812/74611710-5d4e6700-510f-11ea-9531-12ebbf147af8.png)

**Comment by Priler** [comment]
Исправлено.
