### ISSUE TITLE
Небольшой багоотчет + Идеи

### ISSUE THREAD

**Issue by MaximkaProgramist** [Priler/dino3d#25]
Привет хауди! В общем поиграл в динозаврика и вышло неплохо, ты молодец! Но вот нашел пару багов... Первый это проблема смена дня и ночи. При переходе в ночной режим и смерти в нем при перезапуске игры все еще будет ночь(этот баг уже описан на сайте), но из-за этого появился еще одна криповая фигня... Если так и начать играть в ночном моде, то при повторном достижении необходимого кол-ва очков для смены времени суток ночь станет намного темнее (Скрин прилагается). Я неплохо так пересрал когда впервые это заметил XD. 
![12](https://user-images.githubusercontent.com/61155512/74667658-bae8bf00-51b4-11ea-8791-6586cf8adf32.PNG) Остальные баги которые нашел уже оказались изложены на сайте. Поэтому я решил дать тебе пару идей насчет совершенствования игры.. Ну для начала нужно действительно добавить небо. Луна, звезды, солнце, облака. Второе, на мой взгляд, очень необходимое улучшение это возможность поставить игру на паузу. Иногда действительно бывает очень полезно. Ну и еще одно нововведение, которое я хотел бы увидеть в игре - это небольшое расширение геймплея. Пусть это и будет отходить от канонов оригинального динозаврика, но в том случае разработчикам просто не позволяла это сделать плоскость. Я говорю о движениях тирекса влево и вправо. Пусть препятствия можно будет не только перепрыгнуть, но и обойти с одной из сторон. (Типа чтобы вынудить игрока прыгнуть можно сделать ряд из кактусов во всю ширину дорожки, а так одиночные кактусы можно будет обойти.) Чтобы было проще управлять в таком случае, пусть после обхода препятствия дино возвращается ровно на середину дорожки автоматически. В общем то это все. Спасибо за такую замечательную игру и надеюсь ты примешь все что выше к сведению.)

**Comment by MaximkaProgramist** [comment]
(Ред)
Еще раз почитал доску, в общем то о большинстве вопросов ты уже в курсе, но все же нигде не видел последней моей идеи. Мне кажется это будет действительно интересно.

**Comment by Priler** [comment]
Исправлено.
Бег по сторонам пока что не планируется.
