### ISSUE TITLE
Здравствуйте Хауди Хо! Баги и совет

### ISSUE THREAD

**Issue by entit1** [Priler/dino3d#28]
Во время игры встретился с парочкой забавных багов.

Первый заключался в том что после смерти во время ночного времени и после рестарта у меня началась вакханалия, всё было очень тёмным и модели начали покрываться радужными полосками. И после окончания ночи темнота полностью не ушла, а осталось такое ощущение сумерок. (Скрин сделать не успел.)

Второй баг был очень неожиданным и я даже немного испугался. Во время игры один из птеродактилей летел со скоростью пули и при этом обогнал и даже пролетел сквозь модельку другого птеродактиля. Ещё иногда кактусы могут пропадать сами по себе.

Также у меня есть один совет, можно ли добавить какое нибудь оболочки пыли или разлом в земле после приземления динозаврика.

**Comment by Sholokhov99** [comment]
Во время маленького тестирования игры было замечено 2 бага:
1. Впереди меня испарился кактус
2. На меня бежал кактус
Я не знаю, баг или нет, но к сожалению динозавра с трудом видно, когда начинается темнота и при смерти остается.
![chrome_Rbg6pNesnc](https://user-images.githubusercontent.com/28993173/74753086-307e8900-52a2-11ea-91a7-648dab0d6e2a.png)

![chrome_TMOUKB8p15](https://user-images.githubusercontent.com/28993173/74752944-fe6d2700-52a1-11ea-869e-cee6b3ccc336.png)

**Comment by Sholokhov99** [comment]
Пара маленьких багов:
1. При приближении в браузере возникает вот такая штука
2. При уменьшении высоты браузера предметы исчезают раньше того, как окажутся за границей поля видимости
![chrome_xxB4LHkSqh](https://user-images.githubusercontent.com/28993173/74755153-4e012200-52a5-11ea-93b2-fbafe82e0986.png)
![xg3gR100Gu](https://user-images.githubusercontent.com/28993173/74755173-535e6c80-52a5-11ea-98db-d4bbd873363b.png)

**Comment by Artomych-play-2019** [comment]
Хауди Хо портируй игру на телефоны я пробовал играть на своем телефоне не работает прыжок да и вообще не чего не работает на телефоне то я тебе советую добавить поддержку Сенсорный устройств а в целом игра класс

**Comment by Priler** [comment]
Исправлено.
