### ISSUE TITLE
Куда писать про ошибки?

### ISSUE THREAD

**Issue by anmenig** [Priler/dino3d#34]
1. Здесь писать.
2. На почту priler96@gmail.com

**Comment by ElleoMuzz** [comment]
Облегченная версия, птеродактили начали спавнятся с самого начала игры после третьего раунда и вместо кактусов.
![Annotation 2020-02-19 141442](https://user-images.githubusercontent.com/33998060/74811391-fa81e900-5323-11ea-92c3-39d0ec5c6dce.png)
