### ISSUE TITLE
Приложение ВК уже работает.

### ISSUE THREAD

**Issue by anmenig** [Priler/dino3d#36]
Извени но я создал приложение которое работает от https://priler.github.io/dino3d/low.html и от https://priler.github.io/dino3d/

🖥 Для мощных компьютеров - https://vk.com/app7314758
💻 Для слабых компьютеров и ноутбуков - https://vk.com/app7313300

----------

Все скриншоты - https://github.com/anmenig/anmenig.github.io/tree/master/dino3d/images
Если что ты имееш полный доступ. Если что я могу передать группу ВК.

----------
Нужно бы сделать Контактная информация:

- Пользов. соглашение
- Политика конфиденц.

Для ВКонтакте, Фейзбука, Однокласников. Покаместь играть можно в ВКонтакте.

**Comment by Priler** [comment]
Спасибо, но пока что распространение в соц. сетях не планируется.
