### ISSUE TITLE
Cборник багов #1 Бессмертие/Откл. музыки

### ISSUE THREAD

**Issue by URdia** [Priler/dino3d#4]
Когда немного играешь и после переходишь на  другую вкладку динозаврик бежит бессмертно, потом можно спокойно вернуться к вкладке с игрой и играть дальше.

Фоновая музыка выключается при достижении 6к очков.
P.S.
Фоновая музыка начинается когда нажимаешь пробел, а не когда проходят все манипуляции с прогрузом

**Comment by URdia** [comment]
Opera GX / Windows 10 Pro

**Comment by sirynka** [comment]
Пожалуй я оставлю дино бежать, на ночь)

**Comment by Priler** [comment]
Исправлено.
