### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by icoder-new** [Priler/dino3d#53]
Video for see http://file.tj/download.php?file=98420200306_194921.mp4

**Comment by iamcxdev** [comment]
Пишет , что invalid download link
Абдурахман Тугалов здесь , да :)

**Comment by icoder-new** [comment]
@vanproskur Thanks I found really link http://file.tj/download2.php?a=98420200306_194921.mp4&b=bf1f915dce4c0a2ac4b24169b6890334

**Comment by icoder-new** [comment]
@vanproskur  and @Priler 

Sorry ошибка в том что не нажимая на кнопку пробела Dino3D прыгает. Я сделал видос о том что Дино прыгает не нажатия не на каких клавиш

**Comment by iamcxdev** [comment]
You can close it. It is not a bug.
