### ISSUE TITLE
Не появляются припятствия

### ISSUE THREAD

**Issue by MoronPlayYT** [Priler/dino3d#6]
1)Пару скринов
![Снимок экрана (15)](https://user-images.githubusercontent.com/60827315/74091618-636a9500-4aca-11ea-8584-fb9aa98abef4.png
![Снимок экрана (16)](https://user-images.githubusercontent.com/60827315/74091620-6ebdc080-4aca-11ea-9921-569cce110743.png)
![Снимок экрана (17)](https://user-images.githubusercontent.com/60827315/74091623-71b8b100-4aca-11ea-833e-dd16d5daa36b.png)
2)У меня Яндекс Браузер
3)ОС(скрином) :
 ![Снимок экрана (18)](https://user-images.githubusercontent.com/60827315/74091674-fb687e80-4aca-11ea-8a3c-23245b286d83.png)
Играл где-то пол часа, залипал и тут такое )))

**Comment by Priler** [comment]
Проверь сейчас еще раз.
https://priler.github.io/dino3d/
