### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by eone666** [Priler/dino3d#7]
- Постоянно отображается надпись игра закончена и кнопка повтора
![image](https://user-images.githubusercontent.com/28735842/74098149-c990ff80-4b3e-11ea-980e-c5016050d44f.png)
![image](https://user-images.githubusercontent.com/28735842/74098157-ec231880-4b3e-11ea-9406-3e20ee193aeb.png)

- Я до конца не разобрался, но иногда когда еще не стартовал игру, переключил вкладку, вернулся назад и запустил игру запускается только счетчик без самого дино
![image](https://user-images.githubusercontent.com/28735842/74098198-7ec3b780-4b3f-11ea-9509-b70b3f9dd576.png)
------
UPD 

Браузер: Google Chrome

ОС:  Windows 10

---
![image](https://user-images.githubusercontent.com/28735842/74098320-107ff480-4b41-11ea-9758-547bf2b9baa0.png)

**Comment by nedogimov** [comment]
тоже самое.
Браузер: Google Chrome Canary
OC: Windows 10

**Comment by Priler** [comment]
Исправлено.
