### ISSUE TITLE
Рекорд больше 100 000

### ISSUE THREAD

**Issue by kolos-mvi** [Priler/dino3d#8]
Не помещается табло с очками, когда рекорд больше 100 000.

![image](https://user-images.githubusercontent.com/57492101/74105851-2eae1a80-4b6a-11ea-85d5-da6dfba541e0.png)

**Comment by LWJerri** [comment]
Подкручено в исходниках сайта.

**Comment by kolos-mvi** [comment]
Не отрицаю, но это гипотетическая ситуация. В итоге будет кривой дизайн.

**Comment by LWJerri** [comment]
Набрать 10к уже сверх, а 100к невозможно.. В будущем умельцы подрубят ИИ, который сможет когда-то набрать эту цифру..

**Comment by LWJerri** [comment]
В любом случаи находка довольно полезная.

**Comment by KonstantinPankratov** [comment]
Сегодня запулил фикс для этого

**Comment by Kirixo** [comment]
> Набрать 10к уже сверх, а 100к невозможно.. В будущем умельцы подрубят ИИ, который сможет когда-то набрать эту цифру..

у меня как-то багнул этот дино, так что просто пропали все кактусы и птицы, поэтому...
